import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, '..');

const readJson = (filePath) => JSON.parse(fs.readFileSync(filePath, 'utf8'));

test('package exports include entrypoints', () => {
  const pkg = readJson(path.join(packageRoot, 'package.json'));
  assert.ok(pkg.exports['.']);
  assert.equal(pkg.exports['./styles.css'], './src/styles.css');
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'ExplorerApp.tsx')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'thumbnailLoader.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'useThumbnailQueue.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'useAssetInteractions.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'useTopbarScrollState.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'components', 'AssetGrid.tsx')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'components', 'AssetList.tsx')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'components', 'PendingComposeAssetCard.tsx')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'composeJobs.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'usePendingComposeJobs.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'lib', 'gsap.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'ui', 'motion', 'topbarMotion.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'ui', 'motion', 'drawerMotion.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'ui', 'motion', 'modalMotion.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'ui', 'motion', 'toastMotion.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'ui', 'motion', 'topbarSnapBand.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'explorer', 'density', 'createExplorerDensityController.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'explorer', 'density', 'createPinchDensityController.ts')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'src', 'styles.css')));
});

test('standalone app entry exists', () => {
  assert.ok(fs.existsSync(path.join(packageRoot, 'app', 'page.tsx')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'app', 'layout.tsx')));
  assert.ok(fs.existsSync(path.join(packageRoot, 'app', 'not-found.tsx')));
});

test('package app layout owns default App Router not-found fonts and wiring', () => {
  const layoutPath = path.join(packageRoot, 'app', 'layout.tsx');
  const notFoundPath = path.join(packageRoot, 'app', 'not-found.tsx');
  const globalsPath = path.join(packageRoot, 'app', 'globals.css');
  const layout = fs.readFileSync(layoutPath, 'utf8');
  const notFound = fs.readFileSync(notFoundPath, 'utf8');
  const globals = fs.readFileSync(globalsPath, 'utf8');
  assert.ok(layout.includes('fonts.googleapis.com'));
  assert.ok(layout.includes('fonts.gstatic.com'));
  assert.ok(layout.includes("viewportFit: 'cover'"));
  assert.ok(layout.includes("width: 'device-width'"));
  assert.ok(layout.includes('initialScale: 1'));
  assert.ok(globals.includes('--safe-area-top: env(safe-area-inset-top, 0px);'));
  assert.ok(globals.includes('html,'));
  assert.ok(globals.includes('height: 100dvh;'));
  assert.ok(globals.includes('#__next,'));
  assert.ok(globals.includes('overflow: hidden;'));
  assert.ok(globals.includes('touch-action: manipulation;'));
  assert.ok(globals.includes('-webkit-text-size-adjust: 100%;'));
  assert.ok(globals.includes('text-size-adjust: 100%;'));
  assert.ok(globals.includes('padding-top: var(--safe-area-top);'));
  assert.ok(globals.includes('font-size: 16px;'));
  assert.ok(!layout.includes("from 'next/font/google'"));
  assert.ok(notFound.includes('data-explorer-default-not-found="true"'));
  assert.ok(notFound.includes('data-explorer-not-found-scene="multi-phase"'));
  assert.ok(notFound.includes("type Phase = 'idle' | 'warp' | 'arrival' | 'exit';"));
  assert.ok(notFound.includes('uniform float u_envMix;'));
  assert.ok(notFound.includes('uniform float u_warp;'));
  assert.ok(notFound.includes('uniform float u_camZ;'));
  assert.ok(notFound.includes('const didNavigateRef = useRef(false);'));
  assert.ok(notFound.includes("const prefersReducedMotion = useReducedMotionPreference();"));
  assert.ok(notFound.includes("phaseRef.current = 'warp'"));
  assert.ok(notFound.includes("phaseRef.current = 'arrival'"));
  assert.ok(notFound.includes("phaseRef.current = 'exit'"));
  assert.ok(notFound.includes("router.push('/')"));
  assert.ok(notFound.includes("canvas.addEventListener('webglcontextrestored', handleContextRestored);"));
  assert.ok(notFound.includes("arrivalWrap?.classList.add('show');"));
  assert.ok(notFound.includes("voidWrap?.classList.add('arrival-ready');"));
  assert.ok(notFound.includes('requestAnimationFrame(renderScene)'));
  assert.ok(notFound.includes('data-webgl-fallback="true"'));
  assert.ok(notFound.includes('data-webgl-canvas="phase-scene"'));
  assert.ok(!notFound.includes("@import url('https://fonts.googleapis.com"));
});

test('explorer resolves media urls against api base', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const content = fs.readFileSync(explorerPath, 'utf8');
  assert.ok(content.includes('api.buildUrl'));
  assert.ok(content.includes('resolveAssetUrl'));
  assert.ok(content.includes('formatListValue'));
  assert.ok(content.includes('buildUploadUrl'));
  assert.ok(content.includes('handleBulkTag'));
  assert.ok(content.includes('handleComposeSelected'));
  assert.ok(content.includes('AssetPreviewPanel'));
  assert.ok(content.includes('normalizePreviewAsset'));
});

test('preview adapter and panel keep drawer-based preview contract', () => {
  const adapterPath = path.join(packageRoot, 'src', 'previewAdapter.ts');
  const panelPath = path.join(packageRoot, 'src', 'AssetPreviewPanel.tsx');
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const adapter = fs.readFileSync(adapterPath, 'utf8');
  const panel = fs.readFileSync(panelPath, 'utf8');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  assert.ok(adapter.includes('normalizePreviewAsset'));
  assert.ok(adapter.includes('id:'));
  assert.ok(adapter.includes('quick'));
  assert.ok(panel.includes('preview-overlay'));
  assert.ok(panel.includes('onMediaReady'));
  assert.ok(panel.includes('preview-wave'));
  assert.ok(styles.includes('.preview-shell'));
  assert.ok(styles.includes('.preview-overlay.fade'));
  assert.ok(!panel.includes('preview-center-play'));
  assert.ok(panel.includes('preview-scrubber'));
  assert.ok(panel.includes('preview-icon-btn'));
  assert.ok(panel.includes('onObs'));
  assert.ok(panel.includes('onTag'));
  assert.ok(panel.includes('onResolve'));
  assert.ok(panel.includes('onProgramMonitor'));
  assert.ok(panel.includes('stopMediaPlayback'));
  assert.ok(panel.includes('handleOverlayTapToggle'));
  assert.ok(panel.includes('onClick={handleClose}'));
  assert.ok(panel.includes('preview-obs-row'));
  assert.ok(panel.includes('obsMode'));
  assert.ok(styles.includes('.preview-shell'));
  assert.ok(styles.includes('.preview-overlay.fade'));
  assert.ok(styles.includes('.preview-control-row'));
  assert.ok(styles.includes('.preview-center-play'));
  assert.ok(styles.includes('.preview-obs-row'));
  assert.ok(styles.includes('width: min(640px, 100vw);'));
  assert.ok(styles.includes('.preview-shell::after'));
  assert.ok(styles.includes('@media (max-width: 860px){'));
  assert.ok(!styles.includes('max-height: 70vh;'));
});


test('package preview overlay wires semantic action callbacks from ExplorerApp', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const content = fs.readFileSync(explorerPath, 'utf8');
  assert.ok(content.includes('handleFocusedObs'));
  assert.ok(content.includes('handleFocusedTag'));
  assert.ok(content.includes('handleFocusedResolve'));
  assert.ok(content.includes('handleFocusedProgramMonitor'));
  assert.ok(content.includes('onObs={() => { void handleFocusedObs(); }}'));
  assert.ok(content.includes('onTag={() => { void handleFocusedTag(); }}'));
  assert.ok(content.includes('onResolve={() => { void handleFocusedResolve(); }}'));
  assert.ok(content.includes('onProgramMonitor={() => { void handleFocusedProgramMonitor(); }}'));
  assert.ok(content.includes('obsMode={previewObsMode}'));
  assert.ok(content.includes('onObsModeChange={setPreviewObsMode}'));
});

test('normalized preview asset declaration is placed after resolveAssetUrl callback', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const content = fs.readFileSync(explorerPath, 'utf8');
  const resolveIndex = content.indexOf('const resolveAssetUrl = useCallback');
  const thumbSignatureIndex = content.indexOf('const thumbDatasetSignature = useMemo');
  const normalizedIndex = content.indexOf('const normalizedPreviewAsset = useMemo');
  assert.ok(resolveIndex >= 0);
  assert.ok(thumbSignatureIndex > resolveIndex);
  assert.ok(normalizedIndex > resolveIndex);
});

test('explorer api client includes bulk media action endpoints', () => {
  const apiPath = path.join(packageRoot, 'src', 'api.ts');
  const content = fs.readFileSync(apiPath, 'utf8');
  assert.ok(content.includes('bulkDeleteMedia'));
  assert.ok(content.includes("/api/assets/bulk/delete"));
  assert.ok(content.includes('bulkMoveMedia'));
  assert.ok(content.includes("/api/assets/bulk/move"));
  assert.ok(content.includes('bulkTagMedia'));
  assert.ok(content.includes("/api/assets/bulk/tags"));
  assert.ok(content.includes('bulkComposeMedia'));
  assert.ok(content.includes("/api/assets/bulk/compose"));
});

test('api base inference keeps LAN host reachable', () => {
  const utilsPath = path.join(packageRoot, 'src', 'utils.ts');
  const content = fs.readFileSync(utilsPath, 'utf8');
  assert.ok(content.includes('inferApiBaseUrl'));
  assert.ok(content.includes('media-sync-api'));
  assert.ok(content.includes(':8787'));
  assert.ok(content.includes("if (!trimmed) {"));
  assert.ok(content.includes("currentPort !== '8787'"));
});

test('clipboard helper includes fallback copy behavior', () => {
  const utilsPath = path.join(packageRoot, 'src', 'utils.ts');
  const content = fs.readFileSync(utilsPath, 'utf8');
  assert.ok(content.includes('copyTextWithFallback'));
  assert.ok(content.includes("document.execCommand('copy')"));
});

test('media sorting helper orders by recent timestamps', () => {
  const statePath = path.join(packageRoot, 'src', 'state.ts');
  const content = fs.readFileSync(statePath, 'utf8');
  assert.ok(content.includes('sortMediaByRecent'));
  assert.ok(content.includes('updated_at'));
  assert.ok(content.includes('created_at'));
  assert.ok(content.includes('uploaded_at'));
  assert.ok(content.includes('indexed_at'));
  assert.ok(content.includes('filenameTimestamp'));
});

test('explorer supports all-project media view', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const content = fs.readFileSync(explorerPath, 'utf8');
  assert.ok(content.includes('loadAllMedia'));
  assert.ok(content.includes('Media — All Projects'));
  assert.ok(content.includes('buildThumbFallback'));
});

test('asset tile preview open path requires second tap intent and keeps focus separate from selection', () => {
  const hookPath = path.join(packageRoot, 'src', 'useAssetInteractions.ts');
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const gridPath = path.join(packageRoot, 'src', 'components', 'AssetGrid.tsx');
  const listPath = path.join(packageRoot, 'src', 'components', 'AssetList.tsx');
  const hookContent = fs.readFileSync(hookPath, 'utf8');
  const explorer = fs.readFileSync(explorerPath, 'utf8');
  const grid = fs.readFileSync(gridPath, 'utf8');
  const list = fs.readFileSync(listPath, 'utf8');
  assert.ok(hookContent.includes('lastTileTapRef'));
  assert.ok(hookContent.includes('const isSecondTap = prevTap.key === itemKey'));
  assert.ok(hookContent.includes('focusAsset(item, itemKey);'));
  assert.ok(hookContent.includes('if (isSecondTap) {'));
  assert.ok(hookContent.includes('openDrawer(item);'));
  assert.ok(explorer.includes("const [activeAssetKey, setActiveAssetKey] = useState('');"));
  assert.ok(explorer.includes('const focusAsset = useCallback((item: MediaItem, itemKey?: string) => {'));
  assert.ok(explorer.includes('setActiveAssetKey(nextKey);'));
  assert.ok(!explorer.includes(`const focusAsset = useCallback((item: MediaItem, itemKey?: string) => {
    const nextKey = itemKey || assetSelectionKey(item, activeProject);
    if (!nextKey) return;
    setActiveAssetKey(nextKey);
    setFocused(item);`));
  assert.ok(explorer.includes('if (!inspectorOpen || !focused) return null;'));
  assert.ok(explorer.includes('if (!inspectorOpen || !focused) return [];'));
  assert.ok(explorer.includes('const isActive = activeAssetKey === selectionKey;'));
  assert.ok(explorer.includes('const selectionOrderIndex = selectedOrderMap.get(selectionKey) ?? 0;'));
  assert.ok(grid.includes('<img'));
  assert.ok(!grid.includes('<video'));
  assert.ok(list.includes('<img'));
  assert.ok(!list.includes('<video'));
  assert.ok(grid.includes("data-active={viewModel.isActive ? 'true' : 'false'}"));
  assert.ok(list.includes("data-active={viewModel.isActive ? 'true' : 'false'}"));
  assert.ok(list.includes('data-no-preview="1"'));
});

test('topbar interaction boundaries protect header controls and nearby asset selectors', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const utilsPath = path.join(packageRoot, 'src', 'utils.ts');
  const hookPath = path.join(packageRoot, 'src', 'useAssetInteractions.ts');
  const gridPath = path.join(packageRoot, 'src', 'components', 'AssetGrid.tsx');
  const listPath = path.join(packageRoot, 'src', 'components', 'AssetList.tsx');
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const explorer = fs.readFileSync(explorerPath, 'utf8');
  const utils = fs.readFileSync(utilsPath, 'utf8');
  const hook = fs.readFileSync(hookPath, 'utf8');
  const grid = fs.readFileSync(gridPath, 'utf8');
  const list = fs.readFileSync(listPath, 'utf8');
  const styles = fs.readFileSync(stylesPath, 'utf8');

  assert.ok(utils.includes('export function isInteractiveTarget'));
  assert.ok(utils.includes('export function isTopbarOwnedTarget'));
  assert.ok(utils.includes("'[data-topbar-control=\"true\"]'"));
  assert.ok(utils.includes("'summary'"));
  assert.ok(utils.includes("'[data-interactive=\"true\"]'"));
  assert.ok(explorer.includes("const supportsHover = window.matchMedia('(hover: hover) and (pointer: fine)').matches;"));
  assert.ok(explorer.includes("const isTouchPrimary = window.matchMedia('(hover: none) and (pointer: coarse)').matches;"));
  assert.ok(explorer.includes('if (isTouchPrimary) return;'));
  assert.ok(explorer.includes('if (!isTouchPrimary) {'));
  assert.ok(explorer.includes("document.addEventListener('pointerdown', handleOutside);"));
  assert.ok(explorer.includes("document.removeEventListener('pointerdown', handleOutside);"));
  assert.ok(explorer.includes('if (isTopbarOwnedTarget(event.target)) return;'));
  assert.ok(explorer.includes('const pinTopbarTemporarily = useCallback((ms = 900) => {'));
  assert.ok(explorer.includes('topbarIntentRef.current?.setPinned(true);'));
  assert.ok(explorer.includes('topbarIntentRef.current?.setPinned(false);'));
  assert.ok(explorer.includes('onPointerDown={() => pinTopbarTemporarily(900)}'));
  assert.ok(explorer.includes('const mediaContentRef = useRef<HTMLDivElement | null>(null);'));
  assert.ok(explorer.includes('const mediaScrollViewportRef = useRef<HTMLDivElement | null>(null);'));
  assert.ok(explorer.includes("const [topbarMeasuredHeight, setTopbarMeasuredHeight] = useState(0);"));
  assert.ok(explorer.includes('const [topbarHasOpenDropdown, setTopbarHasOpenDropdown] = useState(false);'));
  assert.ok(explorer.includes('const [topbarFocusWithin, setTopbarFocusWithin] = useState(false);'));
  assert.ok(explorer.includes('const topbarInsetPrevRef = useRef(0);'));
  assert.ok(explorer.includes('const updateTopbarMeasuredHeight = () => {'));
  assert.ok(explorer.includes('const observer = new ResizeObserver(() => updateTopbarMeasuredHeight());'));
  assert.ok(explorer.includes("document.addEventListener('gesturestart', blockGesture, listenerOptions);"));
  assert.ok(explorer.includes("document.addEventListener('gesturechange', blockGesture, listenerOptions);"));
  assert.ok(explorer.includes("document.addEventListener('gestureend', blockGesture, listenerOptions);"));
  assert.ok(explorer.includes("document.addEventListener('touchstart', blockMultiTouch, listenerOptions);"));
  assert.ok(explorer.includes("document.addEventListener('touchend', blockDoubleTap, listenerOptions);"));
  assert.ok(explorer.includes('const topbarGap = Number.parseFloat(styles.getPropertyValue(\'--topbar-gap\')) || 0;'));
  assert.ok(explorer.includes('const nextInset = Math.max(0, topbarMeasuredHeight + topbarGap);'));
  assert.ok(explorer.includes('const delta = nextInset - topbarInsetPrevRef.current;'));
  assert.ok(explorer.includes('suppressAutoToggle();'));
  assert.ok(explorer.includes('scrollEl.scrollTop = Math.max(0, scrollEl.scrollTop + delta);'));
  assert.ok(explorer.includes('|| actionsOpen'));
  assert.ok(explorer.includes('|| topbarHasOpenDropdown'));
  assert.ok(explorer.includes('|| topbarFocusWithin'));
  assert.ok(explorer.includes("topbar.addEventListener('toggle', handleDropdownToggle, true);"));
  assert.ok(explorer.includes("topbar.removeEventListener('toggle', handleDropdownToggle, true);"));
  assert.ok(explorer.includes('rootRef: mediaContentRef,'));
  assert.ok(explorer.includes('scrollRef: mediaScrollViewportRef,'));
  assert.ok(explorer.includes('ref={mediaContentRef}'));
  assert.ok(explorer.includes('ref={mediaScrollViewportRef}'));
  assert.ok(explorer.includes('className="scroll"'));
  assert.ok(explorer.includes("data-topbar-hidden={topbarHidden ? 'true' : 'false'}"));
  assert.ok(explorer.includes("style={{ '--topbar-measured-height': `${topbarMeasuredHeight}px` } as React.CSSProperties}"));
  assert.ok(explorer.includes('data-topbar-root="true"'));
  assert.ok(explorer.includes('data-topbar-panel="true"'));
  assert.ok(explorer.includes('<div className="topbar-anchor" aria-hidden="true">'));
  assert.ok(explorer.includes('className="scroll-content"'));
  assert.ok(explorer.includes("'--scroll-content-top-inset': 'calc(var(--topbar-measured-height) + var(--topbar-gap))'"));
  assert.ok(explorer.includes("'calc(var(--topbar-measured-height) + var(--topbar-gap))'"));
  assert.ok(explorer.includes('data-topbar-control="true"'));
  assert.ok(explorer.includes('data-interactive="true"'));
  assert.ok(explorer.includes('<div className="search" role="search" data-interactive="true" data-topbar-control="true">'));
  assert.ok(explorer.includes('className={`actions-panel ${actionsOpen ? \'open\' : \'\'}`} role="region" aria-label="Explorer actions" data-interactive="true" data-topbar-panel="true"'));
  assert.ok(hook.includes('if (isInteractiveTarget(event.target)) return;'));
  assert.ok(grid.includes('onPointerDown={handleTogglePointerDown}'));
  assert.ok(grid.includes('event.stopPropagation();'));
  assert.ok(list.includes('data-interactive="true"'));
  assert.ok(styles.includes('.topbar-anchor{'));
  assert.ok(styles.includes('position: sticky;'));
  assert.ok(styles.includes('height: 0;'));
  assert.ok(styles.includes('z-index: 120;'));
  assert.ok(styles.includes('.topbar > .section-h{'));
  assert.ok(styles.includes('pointer-events: none;'));
  assert.ok(styles.includes('z-index: 31;'));
  assert.ok(styles.includes('z-index: 30;'));
  assert.ok(styles.includes('pointer-events: auto;'));
  assert.ok(styles.includes('.content .scroll{'));
  assert.ok(styles.includes('.masonry-columns{'));
});

test('pending compose recovery reconciles stale restored jobs and prefers real assets over zombie placeholders', () => {
  const hookPath = path.join(packageRoot, 'src', 'usePendingComposeJobs.ts');
  const jobsPath = path.join(packageRoot, 'src', 'composeJobs.ts');
  const hook = fs.readFileSync(hookPath, 'utf8');
  const jobs = fs.readFileSync(jobsPath, 'utf8');

  assert.ok(hook.includes('RESTORED_PENDING_COMPOSE_RECOVERY_MS = 8_000'));
  assert.ok(hook.includes('RESTORED_PENDING_COMPOSE_MAX_ATTEMPTS = 2'));
  assert.ok(hook.includes('pendingComposeMatchesMediaItem'));
  assert.ok(hook.includes('const hasConfirmedOutput = useCallback'));
  assert.ok(hook.includes('item.recoveredFromStorage'));
  assert.ok(hook.includes('hasConfirmedOutput(item)'));
  assert.ok(hook.includes('setItems((prev) => prev.filter((x) => x.jobId !== item.jobId))'));
  assert.ok(jobs.includes('status?: PendingComposeViewStatus;'));
  assert.ok(jobs.includes('recoveredFromStorage?: boolean;'));
  assert.ok(jobs.includes('pendingComposeCandidateOutputPaths'));
  assert.ok(jobs.includes('pendingComposeMatchesMediaItem'));
});

test('compose action filters selected assets to videos', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const content = fs.readFileSync(explorerPath, 'utf8');
  assert.ok(content.includes("selectionItems.filter((item) => guessKind(item) === 'video')"));
  assert.ok(content.includes('Select one or more video clips'));
  assert.ok(content.includes("addToast('warn', 'Compose', 'Select one or more clips')"));
  assert.ok(content.includes('const buildComposeTimestampName = () => {'));
  assert.ok(content.includes("entry?.name === 'P5-SHARED-Exported-Media'"));
  assert.ok(content.includes('setComposeModalOpen(true);'));
  assert.ok(content.includes('{composeModalRendered ? ('));
  assert.ok(content.includes('className="compose-modal open"'));
  assert.ok(content.includes('const [composeSubmitting, setComposeSubmitting] = useState(false);'));
  assert.ok(content.includes('data-compose-project-picker="1"'));
  assert.ok(content.includes('onSubmit={(event) => {'));
  assert.ok(content.includes('className="btn good" type="submit" disabled={composeSubmitting}'));
  assert.ok(content.includes("registerAcceptedJob({ envelope: response as ComposeJobEnvelope });"));
  assert.ok(content.includes("addToast('good', 'Compose', 'Compose started');"));
  assert.ok(content.includes("addToast('good', 'Compose', 'Compose completed');"));
  assert.ok(content.includes("addToast('bad', 'Compose', 'Compose failed');"));
  assert.ok(content.includes('target_dir: \'exports\''));
  assert.ok(content.includes("mode: 'encode'"));
  assert.ok(content.includes('allow_overwrite: false,'));
  assert.ok(content.includes('if (composeSubmitting) {'));
  assert.ok(content.includes('setComposeSubmitting(true);'));
  assert.ok(content.includes('setComposeSubmitting(false);'));
  assert.ok(content.includes("{composeSubmitting ? 'Composing...' : 'Compose'}"));
  assert.ok(content.includes('disabled={composeSubmitting}'));
  assert.ok(content.includes('aria-busy={composeSubmitting}'));
  assert.ok(content.includes("pollIntervalMs: 2000,"));
  assert.ok(content.includes("const visiblePendingComposeItems = useMemo(() => {"));
  assert.ok(content.includes("return sortPendingComposeItemsForDisplay(relevant);"));
  assert.ok(content.includes("const pendingEntries = useMemo<PendingRenderedEntry[]>(() => visiblePendingComposeItems.map((pendingItem) => ({"));
  assert.ok(content.includes("...pendingEntries,"));
  assert.ok(content.includes("...assetEntries,"));
  assert.ok(content.includes("if (item.status === 'finalizing' && previousStatus && previousStatus !== 'finalizing') {"));
  assert.ok(content.includes("if (item.status !== 'finalizing') return;"));
  assert.ok(content.includes("if (visible) {"));
  assert.ok(content.includes("removePendingJob(item.jobId);"));
  const composeStart = content.indexOf('const handleComposeSelected = useCallback(async () => {');
  const composeEnd = content.indexOf('const handleComposeConfirm = useCallback(async () => {', composeStart);
  assert.ok(composeStart >= 0);
  assert.ok(composeEnd > composeStart);
  const composeBlock = content.slice(composeStart, composeEnd);
  assert.ok(!composeBlock.includes('window.prompt('));
  const confirmEnd = content.indexOf('const handleResolve = useCallback(async () => {', composeEnd);
  const confirmBlock = content.slice(composeEnd, confirmEnd);
  assert.ok(confirmBlock.includes("mode: 'encode'"));
  assert.ok(!confirmBlock.includes("mode: 'auto'"));
  assert.ok(confirmBlock.includes("registerAcceptedJob({ envelope: response as ComposeJobEnvelope });"));
  assert.ok(!confirmBlock.includes('await loadProjects();'));
  assert.ok(!confirmBlock.includes('await loadAllMedia();'));
  assert.ok(!confirmBlock.includes('await loadMedia(activeProject);'));
  assert.ok(confirmBlock.includes('} finally {'));
});

test('pending compose modules and render wiring are present', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const gridPath = path.join(packageRoot, 'src', 'components', 'AssetGrid.tsx');
  const listPath = path.join(packageRoot, 'src', 'components', 'AssetList.tsx');
  const cardPath = path.join(packageRoot, 'src', 'components', 'PendingComposeAssetCard.tsx');
  const hookPath = path.join(packageRoot, 'src', 'usePendingComposeJobs.ts');
  const jobsPath = path.join(packageRoot, 'src', 'composeJobs.ts');
  const explorer = fs.readFileSync(explorerPath, 'utf8');
  const grid = fs.readFileSync(gridPath, 'utf8');
  const list = fs.readFileSync(listPath, 'utf8');
  const card = fs.readFileSync(cardPath, 'utf8');
  const hook = fs.readFileSync(hookPath, 'utf8');
  const jobs = fs.readFileSync(jobsPath, 'utf8');

  assert.ok(explorer.includes("const {\n    pendingComposeItems,\n    registerAcceptedJob,\n    removePendingJob,\n  } = usePendingComposeJobs({"));
  assert.ok(explorer.includes("fetchJson: fetchComposeJobJson,"));
  assert.ok(explorer.includes("onCompletedRefreshScope: async (refreshScope) => {"));
  assert.ok(explorer.includes("masonryColumns={masonryRenderColumns}"));
  assert.ok(explorer.includes("items={renderedMediaEntries}"));
  assert.ok(explorer.includes("onDismissPendingJob={removePendingJob}"));
  assert.ok(explorer.includes("() => prependItemsIntoMasonryColumns<RenderedMediaEntry>("));
  assert.ok(explorer.includes("const hydrateProjectMediaItems = useCallback((items: MediaItem[], project: { name: string; source?: string | null }): MediaItem[] => ("));
  assert.ok(explorer.includes('mergeMediaItemsPreservingIdentity(current, hydratedItems)'));
  assert.ok(explorer.includes('buildMediaIdentityKey(item, projectOverride)'));
  assert.ok(explorer.includes("const safeThumbUrl = thumbUrl && getThumbLoadState(thumbJobKey) !== 'error'"));
  assert.ok(grid.includes("import PendingComposeAssetCard, { type PendingComposeAsset } from './PendingComposeAssetCard';"));
  assert.ok(grid.includes("if (entry.kind === 'pending') {"));
  assert.ok(list.includes("import PendingComposeAssetCard, { type PendingComposeAsset } from './PendingComposeAssetCard';"));
  assert.ok(list.includes("if (entry.kind === 'pending') {"));
  assert.ok(card.includes('data-pending-compose-card="true"'));
  assert.ok(card.includes('function PendingComposeWaterSvg({'));
  assert.ok(card.includes('data-water-svg="true"'));
  assert.ok(card.includes('const REAR_WAVE_PATH ='));
  assert.ok(card.includes('const FRONT_WAVE_PATH ='));
  assert.ok(card.includes('window.requestAnimationFrame(tick)'));
  assert.ok(card.includes('status !== "failed"'));
  assert.ok(card.includes('badge: "QUEUED"'));
  assert.ok(card.includes('badge: "TAKING LONGER"'));
  assert.ok(card.includes('badge: "RECONNECTING"'));
  assert.ok(card.includes('badge: "FINALIZING"'));
  assert.ok(card.includes('badge: "FAILED"'));
  assert.ok(card.includes('footer: "waiting to resume"'));
  assert.ok(card.includes('data-pending-compose-dismiss="true"'));
  assert.ok(card.includes('debug artifacts preserved'));
  assert.ok(card.includes('.pending-compose-water-svg'));
  assert.ok(card.includes('const BODY_FILL_FLOOR = 420;'));
  assert.ok(card.includes('linearGradient id={bodyGradientId}'));
  assert.ok(card.includes('stopOpacity="0.8"'));
  assert.ok(card.includes('stopOpacity="0.04"'));
  assert.ok(card.includes('stroke="#ffffff"'));
  assert.ok(card.includes('strokeOpacity="0.18"'));
  assert.ok(card.includes('transform="translate(0 -1.5)"'));
  assert.ok(card.includes('const bobAmplitude = status === "running_long" ? 3.5 : 4.75;'));
  assert.ok(card.includes('solid: "#2aa8ff"'));
  assert.ok(card.includes('solid: "#ff9b1e"'));
  assert.ok(card.includes('solid: "#7868ff"'));
  assert.ok(card.includes('solid: "#db4343"'));
  assert.ok(!card.includes('solid: "rgba('));
  assert.ok(!card.includes('pending-compose-water-wrap'));
  assert.ok(!card.includes('function Wave({'));
  assert.ok(!card.includes('const WAVE_PATH ='));
  assert.ok(hook.includes('pollIntervalMs = 2000'));
  assert.ok(hook.includes('const [items, setItems] = useState<PendingComposeItem[]>(() => readPersistedPendingComposeItems());'));
  assert.ok(hook.includes('window.localStorage.getItem(PENDING_COMPOSE_STORAGE_KEY)'));
  assert.ok(hook.includes('window.localStorage.setItem('));
  assert.ok(hook.includes('window.localStorage.removeItem(PENDING_COMPOSE_STORAGE_KEY);'));
  assert.ok(hook.includes('const active = current.filter('));
  assert.ok(hook.includes('|| item.status === "reconnecting"'));
  assert.ok(hook.includes('if (nextStatus === "completed") {'));
  assert.ok(hook.includes('status: "finalizing"'));
  assert.ok(hook.includes('status: "reconnecting"'));
  assert.ok(hook.includes('pendingComposeReconnectDelayMs(attemptCount, pollIntervalMs)'));
  assert.ok(hook.includes('error: undefined,'));
  assert.ok(jobs.includes('if (elapsedMs > 45_000) return "running_long";'));
  assert.ok(jobs.includes('|| status === "reconnecting"'));
  assert.ok(jobs.includes('PENDING_COMPOSE_STORAGE_KEY'));
  assert.ok(jobs.includes('restorePendingComposeItemsFromStorage'));
  assert.ok(jobs.includes('serializePendingComposeItemsForStorage'));
});

test('package explorer delete actions route through custom confirmation modal', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const content = fs.readFileSync(explorerPath, 'utf8');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  assert.ok(content.includes('const [deleteModalOpen, setDeleteModalOpen] = useState(false);'));
  assert.ok(content.includes('const [pendingDeleteSelectionKeys, setPendingDeleteSelectionKeys] = useState<string[]>([]);'));
  assert.ok(content.includes('const performDeleteMediaSelection = useCallback('));
  assert.ok(content.includes('const deleteMediaSelection = useCallback((selectionKeys: string[]) => {'));
  assert.ok(content.includes('setPendingDeleteSelectionKeys(resolveSelectionKeysForItems(items));'));
  assert.ok(content.includes('setDeleteModalOpen(true);'));
  assert.ok(content.includes('const handleDeleteConfirm = useCallback(async () => {'));
  assert.ok(content.includes('await performDeleteMediaSelection(selectionKeys);'));
  assert.ok(content.includes('const handleDeleteCancel = useCallback(() => {'));
  assert.ok(content.includes('setPendingDeleteSelectionKeys([]);'));
  assert.ok(content.includes('{deleteModalRendered ? ('));
  assert.ok(content.includes('className="confirm-modal open"'));
  assert.ok(content.includes('id="confirmDeleteTitle" className="confirm-title"'));
  assert.ok(content.includes("pendingDeleteSelectionKeys.length === 1 ? 'Delete this asset?' : `Delete ${Math.max(1, pendingDeleteSelectionKeys.length)} assets?`"));
  assert.ok(content.includes('onClick={() => deleteMediaSelection(selectedKeysOrdered)}'));
  assert.ok(content.includes("handler: () => deleteMediaSelection(resolveSelectionKeysForItems(items)),"));
  assert.ok(content.includes("onDelete={() => { if (focused) void deleteMediaSelection([assetSelectionKey(focused, activeProject)]); }}"));
  assert.ok(content.includes('if (deleteSubmitting) return;'));
  assert.ok(content.includes("{deleteSubmitting ? 'Deleting...' : 'Delete'}"));
  assert.ok(!content.includes('window.confirm'));
  const deleteStart = content.indexOf('const deleteMediaSelection = useCallback((selectionKeys: string[]) => {');
  const confirmStart = content.indexOf('const handleDeleteConfirm = useCallback(async () => {', deleteStart);
  assert.ok(deleteStart >= 0);
  assert.ok(confirmStart > deleteStart);
  const deleteBlock = content.slice(deleteStart, confirmStart);
  assert.ok(!deleteBlock.includes('await api.bulkDeleteMedia(refs);'));
  const confirmEnd = content.indexOf('const handleDeleteCancel = useCallback(() => {', confirmStart);
  const confirmBlock = content.slice(confirmStart, confirmEnd);
  assert.ok(confirmBlock.includes('await performDeleteMediaSelection(selectionKeys);'));
  assert.ok(styles.includes('.confirm-modal{'));
  assert.ok(styles.includes('.confirm-card{'));
  assert.ok(styles.includes('z-index: 126;'));
  assert.ok(styles.includes('pointer-events: auto;'));
});

test('package explorer compose modal styles are present', () => {
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  assert.ok(styles.includes('.compose-modal{'));
  assert.ok(styles.includes('.compose-card{'));
  assert.ok(styles.includes('.compose-field select{'));
  assert.ok(styles.includes('env(safe-area-inset-top)'));
});

test('topbar dropdown and sidebar scroll contracts avoid clipping and preserve pane-owned scrolling', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const explorer = fs.readFileSync(explorerPath, 'utf8');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  assert.ok(styles.includes('.topbar{'));
  assert.ok(styles.includes('isolation: isolate;'));
  assert.ok(styles.includes('overflow: visible;'));
  assert.ok(!styles.includes('contain: paint;'));
  assert.ok(styles.includes('.sidebar.sidebar-drawer{'));
  assert.ok(styles.includes('touch-action: pan-y;'));
  assert.ok(styles.includes('.sidebar .scroll{'));
  assert.ok(styles.includes('height: 100%;'));
  assert.ok(styles.includes('overflow-y: auto;'));
  assert.ok(styles.includes('overscroll-behavior-y: contain;'));
  assert.ok(explorer.includes('className={`backdrop sidebar-backdrop ${sidebarOpen ? \'show\' : \'\'}`}'));
  assert.ok(styles.includes('.sidebar-backdrop{'));
  assert.ok(styles.includes('left: min(420px, calc(100vw - 24px));'));
  assert.ok(styles.includes('@media (max-width: 860px){'));
  assert.ok(styles.includes('body{ overflow:hidden; }'));
});

test('brand area still toggles the project panel and is not blocked by reveal layers', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const explorer = fs.readFileSync(explorerPath, 'utf8');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  assert.ok(explorer.includes('const toggleSidebarOpen = useCallback(() => {'));
  assert.ok(explorer.includes("className={`brand ${sidebarOpen ? 'projects-open' : ''}`}"));
  assert.ok(explorer.includes('role="button"'));
  assert.ok(explorer.includes('tabIndex={0}'));
  assert.ok(explorer.includes('onClick={toggleSidebarOpen}'));
  assert.ok(explorer.includes("if (event.key !== 'Enter' && event.key !== ' ') return;"));
  assert.ok(styles.includes('.brand{'));
  assert.ok(styles.includes('cursor: pointer;'));
  assert.ok(styles.includes('pointer-events: auto;'));
  assert.ok(!styles.includes('.topbar-reveal{'));
  assert.ok(styles.includes('pointer-events: none;'));
});

test('static explorer uses OBS push helper', () => {
  const explorerPath = path.resolve(packageRoot, '..', '..', '..', 'public', 'explorer.html');
  const content = fs.readFileSync(explorerPath, 'utf8');
  assert.ok(content.includes('obsPushBrowserMedia'));
  assert.ok(!content.includes('resolveObsInputName'));
});

test('static OBS player page exists', () => {
  const playerPath = path.resolve(packageRoot, '..', '..', '..', 'public', 'player.html');
  const content = fs.readFileSync(playerPath, 'utf8');
  assert.ok(content.includes('OBS Player'));
  assert.ok(content.includes('object-fit'));
});

test('OBS websocket helper includes browser source defaults', () => {
  const obsPath = path.resolve(packageRoot, '..', '..', '..', 'public', 'js', 'obs-push.js');
  const content = fs.readFileSync(obsPath, 'utf8');
  assert.ok(content.includes('obsPushBrowserMedia'));
  assert.ok(content.includes('CreateInput'));
  assert.ok(content.includes('SetInputSettings'));
  assert.ok(content.includes('already exists'));
  assert.ok(content.includes('resolveInputName'));
  assert.ok(content.includes('cleanupExtraInputs'));
  assert.ok(content.includes('ensureBrowserInput'));
  assert.ok(content.includes('GetVideoSettings'));
  assert.ok(content.includes('GetInputSettings'));
  assert.ok(content.includes('snapBrowserSourceToCanvas'));
  assert.ok(content.includes('outputWidth'));
  assert.ok(content.includes('TOP_LEFT_ALIGNMENT'));
  assert.ok(content.includes('SetSceneItemTransform'));
  assert.ok(content.includes('reroute_audio'));
});

test('explorer queues thumbnail loads from server urls', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const gridPath = path.join(packageRoot, 'src', 'components', 'AssetGrid.tsx');
  const loaderPath = path.join(packageRoot, 'src', 'thumbnailLoader.ts');
  const hookPath = path.join(packageRoot, 'src', 'useThumbnailQueue.ts');
  const statePath = path.join(packageRoot, 'src', 'state.ts');
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const content = fs.readFileSync(explorerPath, 'utf8');
  const gridContent = fs.readFileSync(gridPath, 'utf8');
  const loaderContent = fs.readFileSync(loaderPath, 'utf8');
  const hookContent = fs.readFileSync(hookPath, 'utf8');
  const stateContent = fs.readFileSync(statePath, 'utf8');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  assert.ok(content.includes('useThumbnailQueue({'));
  assert.ok(content.includes('thumbDatasetSignature'));
  assert.ok(content.includes('buildThumbJobKey('));
  assert.ok(gridContent.includes('data-thumb-url'));
  assert.ok(content.includes('CONTENT_LOADING_DELAY_MS'));
  assert.ok(content.includes('pendingDataLoadOverlay'));
  assert.ok(content.includes('dynamicOrientations'));
  assert.ok(content.includes('resolveItemOrientation'));
  assert.ok(content.includes('buildMasonryColumns'));
  assert.ok(gridContent.includes('masonryColumns.map((column, columnIndex) => ('));
  assert.ok(gridContent.includes('--masonry-column-count'));
  assert.ok(stateContent.includes('export function buildMasonryColumns'));
  assert.ok(styles.includes('.masonry-columns{'));
  assert.ok(styles.includes('.masonry-column{'));
  assert.ok(styles.includes('-webkit-touch-callout: none;'));
  assert.ok(!styles.includes('column-fill: balance;'));
  assert.ok(content.includes('beginContentLoading'));
  assert.ok(content.includes('endContentLoading'));
  assert.ok(loaderContent.includes('export const THUMB_LOAD_TIMEOUT_MS = 8000;'));
  assert.ok(loaderContent.includes('thumbLoadStateCache'));
  assert.ok(loaderContent.includes('thumbLoadedKey'));
  assert.ok(hookContent.includes('requiresThumbNodeSync'));
  assert.ok(hookContent.includes('hasPendingThumbNetworkLoad'));
  assert.ok(content.includes('project_source'));
});

test('package explorer interaction handlers do not trigger loading overlay state', () => {
  const hookPath = path.join(packageRoot, 'src', 'useAssetInteractions.ts');
  const content = fs.readFileSync(hookPath, 'utf8');
  const start = content.indexOf('const buildAssetPointerHandlers = useCallback(');
  const end = content.indexOf('return {', start);
  assert.ok(start >= 0);
  assert.ok(end > start);
  const block = content.slice(start, end);
  assert.ok(block.includes('openDrawer(item);'));
  assert.ok(block.includes('openContextMenu(event.clientX, event.clientY, resolveContextItems())'));
  assert.ok(block.includes('event.stopPropagation();'));
  assert.ok(!block.includes('setPendingDataLoadOverlay('));
  assert.ok(!block.includes('setContentLoading(true)'));
});

test('package explorer context menu opens only on deliberate long press or context click', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const hookPath = path.join(packageRoot, 'src', 'useAssetInteractions.ts');
  const explorerContent = fs.readFileSync(explorerPath, 'utf8');
  const content = fs.readFileSync(hookPath, 'utf8');
  const start = content.indexOf('const buildAssetPointerHandlers = useCallback(');
  const end = content.indexOf('return {', start);
  assert.ok(start >= 0);
  assert.ok(end > start);
  const block = content.slice(start, end);
  assert.ok(content.includes('const LONG_PRESS_MS = 620;'));
  assert.ok(content.includes('const LONG_PRESS_MOVE_CANCEL_PX = 12;'));
  assert.ok(block.includes("if (event.pointerType === 'touch' || event.pointerType === 'pen')"));
  assert.ok(block.includes('longPressTimerRef.current = window.setTimeout(() => {'));
  assert.ok(block.includes('longPressFiredRef.current = true;'));
  assert.ok(block.includes('const movedFar = (dx * dx + dy * dy) > LONG_PRESS_MOVE_CANCEL_PX * LONG_PRESS_MOVE_CANCEL_PX;'));
  assert.ok(block.includes('if (movedFar) {'));
  assert.ok(block.includes('if (longPressFired) {'));
  assert.ok(block.includes('if (event.pointerType === \'touch\' || event.pointerType === \'pen\') {'));
  assert.ok(block.includes('if (event.pointerType === \'mouse\' && event.button !== 0) return;'));
  assert.ok(explorerContent.includes('onScroll={clearPendingLongPress}'));
});

test('package explorer grid capture suppresses native context menu in asset zones', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const gridPath = path.join(packageRoot, 'src', 'components', 'AssetGrid.tsx');
  const listPath = path.join(packageRoot, 'src', 'components', 'AssetList.tsx');
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const content = fs.readFileSync(explorerPath, 'utf8');
  const gridContent = fs.readFileSync(gridPath, 'utf8');
  const listContent = fs.readFileSync(listPath, 'utf8');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  assert.ok(content.includes('onContextMenuCapture={(event) => {'));
  assert.ok(content.includes("if (!target?.closest('.asset, .row')) return;"));
  assert.ok(content.includes('event.preventDefault();'));
  assert.ok(content.includes('event.stopPropagation();'));
  assert.ok(gridContent.includes('onContextMenu={(event) => {'));
  assert.ok(gridContent.includes('onDragStart={(event) => event.preventDefault()}'));
  assert.ok(gridContent.includes('draggable={false}'));
  assert.ok(listContent.includes('onContextMenu={(event) => {'));
  assert.ok(listContent.includes('onDragStart={(event) => event.preventDefault()}'));
  assert.ok(gridContent.includes('asset-interactive-surface'));
  assert.ok(listContent.includes('asset-interactive-surface'));
  assert.ok(content.includes('custom-ui-surface'));
  assert.ok(styles.includes('.asset-interactive-surface,'));
  assert.ok(styles.includes('.custom-ui-surface,'));
  assert.ok(styles.includes('-webkit-touch-callout: none;'));
  assert.ok(styles.includes('-webkit-tap-highlight-color: transparent;'));
  assert.ok(styles.includes('.tile-ui-text{'));
});


test('package explorer keeps form controls usable while suppressing native selection on custom surfaces', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const previewPath = path.join(packageRoot, 'src', 'AssetPreviewPanel.tsx');
  const content = fs.readFileSync(explorerPath, 'utf8');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  const preview = fs.readFileSync(previewPath, 'utf8');
  assert.ok(content.includes('className={`content custom-ui-surface'));
  assert.ok(content.includes('className={`selectbar custom-ui-surface'));
  assert.ok(content.includes('className="context-menu open custom-ui-surface"'));
  assert.ok(styles.includes('.custom-ui-surface input,'));
  assert.ok(styles.includes('.custom-ui-surface textarea,'));
  assert.ok(styles.includes('.custom-ui-surface select,'));
  assert.ok(styles.includes('.custom-ui-surface [contenteditable="true"],'));
  assert.ok(styles.includes('-webkit-user-select: text;'));
  assert.ok(styles.includes('.custom-ui-surface button,'));
  assert.ok(preview.includes('draggable={false}'));
  assert.ok(preview.includes('onDragStart={(event) => event.preventDefault()}'));
});

test('package explorer context menu styles are explicit and stable', () => {
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  assert.ok(styles.includes('.context-menu{'));
  assert.ok(styles.includes('font-family: Inter, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;'));
  assert.ok(styles.includes('font-size: 17px;'));
  assert.ok(styles.includes('line-height: 1.3;'));
  assert.ok(styles.includes('-webkit-text-size-adjust: 100%;'));
  assert.ok(styles.includes('text-size-adjust: 100%;'));
  assert.ok(styles.includes('width: min(320px, calc(100vw - 24px));'));
  assert.ok(styles.includes('.context-menu button:focus-visible'));
});

test('package explorer data load paths explicitly request loading overlay ownership', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const hookPath = path.join(packageRoot, 'src', 'useThumbnailQueue.ts');
  const content = fs.readFileSync(explorerPath, 'utf8');
  const hookContent = fs.readFileSync(hookPath, 'utf8');
  assert.ok(content.includes('setPendingDataLoadOverlay(true);'));
  assert.ok(content.includes('setPendingDataLoadOverlay(false);'));
  assert.ok(hookContent.includes('const shouldShowOverlay = pendingDataLoadOverlay && syncTargets.some((target) => hasPendingThumbNetworkLoad(target));'));
  assert.ok(hookContent.includes('const loadingToken = shouldShowOverlay ? beginContentLoading() : 0;'));
  assert.ok(hookContent.includes('clearPendingDataLoadOverlay();'));
});


test('package explorer uses static-parity asset interaction semantics', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const hookPath = path.join(packageRoot, 'src', 'useAssetInteractions.ts');
  const gridPath = path.join(packageRoot, 'src', 'components', 'AssetGrid.tsx');
  const content = fs.readFileSync(explorerPath, 'utf8');
  const hookContent = fs.readFileSync(hookPath, 'utf8');
  const gridContent = fs.readFileSync(gridPath, 'utf8');
  assert.ok(gridContent.includes('data-no-preview="1"'));
  assert.ok(hookContent.includes('if (inNoPreviewZone(event.target)) return;'));
  assert.ok(hookContent.includes('if (inspectorOpen) {'));
  assert.ok(hookContent.includes('closeDrawer();'));
  assert.ok(hookContent.includes('openDrawer(item);'));
  assert.ok(content.includes('toggleSelectionWithOrder'));
  assert.ok(content.includes('selectionOrderIndexMap'));
  assert.ok(content.includes('selectedOrderMap.get(selectionKey)'));
});

test('package explorer suppresses default context menu in tile preview zone', () => {
  const hookPath = path.join(packageRoot, 'src', 'useAssetInteractions.ts');
  const content = fs.readFileSync(hookPath, 'utf8');
  assert.ok(content.includes('const handleContextMenu = (event: React.MouseEvent<HTMLElement>) => {'));
  assert.ok(content.includes('event.preventDefault();'));
  assert.ok(content.includes('openContextMenu(event.clientX, event.clientY, resolveContextItems())'));
});

test('package explorer styles include static-parity selected glow and order badge', () => {
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  assert.ok(styles.includes('.asset.is-selected'));
  assert.ok(styles.includes('rgba(74,240,192,0.92)'));
  assert.ok(styles.includes('.selector .sel-order'));
  assert.ok(styles.includes('.asset.is-selected .selector .sel-order'));
});


test('package explorer topbar layout follows static two-row structure', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const hookPath = path.join(packageRoot, 'src', 'useTopbarScrollState.ts');
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const content = fs.readFileSync(explorerPath, 'utf8');
  const hookContent = fs.readFileSync(hookPath, 'utf8');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  assert.ok(content.includes('className="topbar"'));
  assert.ok(content.includes('<div className="section-h">'));
  assert.ok(content.includes('aria-label="Toggle projects panel"'));
  assert.ok(!content.includes('className="btn mobile-only"'));
  assert.ok(styles.includes('--topbar-subrow-height'));
  assert.ok(styles.includes('--topbar-gap: 12px;'));
  assert.ok(styles.includes('--topbar-measured-height: var(--topbar-height);'));
  assert.ok(!styles.includes('--topbar-offset-open'));
  assert.ok(!styles.includes('--topbar-offset-hidden'));
  assert.ok(!styles.includes('.app.topbar-hidden{'));
  assert.ok(styles.includes('margin: 0;'));
  assert.ok(styles.includes('.topbar::before{'));
  assert.ok(styles.includes('background: transparent;'));
  assert.ok(styles.includes('.topbar-inner{'));
  assert.ok(styles.includes('z-index: 4;'));
  assert.ok(styles.includes('.section-h{'));
  assert.ok(styles.includes('.topbar > .section-h{'));
  assert.ok(styles.includes('pointer-events: none;'));
  assert.ok(styles.includes('.brand.projects-open .brand-title.is-secondary'));
  assert.ok(styles.includes('padding: 0;'));
  assert.ok(styles.includes('.scroll-content{'));
  assert.ok(styles.includes('transition: none;'));
  assert.ok(styles.includes('padding-top: var(--scroll-content-top-inset, 0px);'));
  assert.ok(!styles.includes('.scroll-content.topbar-open{'));
  assert.ok(!styles.includes('.scroll-content.topbar-hidden{'));
  assert.ok(styles.includes('.content .scroll{'));
  assert.ok(styles.includes('padding: 0;'));
  assert.ok(styles.includes('touch-action: pan-y;'));
  assert.ok(content.includes('useTopbarScrollState({'));
  assert.ok(content.includes('createTopbarMotion(topbarEl)'));
  assert.ok(content.includes('createTopbarSnapBand({'));
  assert.ok(content.includes('createDrawerMotion(drawerEl, backdropEl, {'));
  assert.ok(content.includes('const modeQuery = window.matchMedia(\'(max-width: 860px)\');'));
  assert.ok(content.includes("getMode: () => (modeQuery.matches ? 'sheet' : 'side')"));
  assert.ok(content.includes('controller.syncLayoutMode();'));
  assert.ok(content.includes('let hasBootstrappedExplorerSession = false;'));
  assert.ok(content.includes('if (hasBootstrappedExplorerSession) return;'));
  assert.ok(content.includes('hasBootstrappedExplorerSession = true;'));
  assert.ok(content.includes('const liveIds = new Set(toasts.map((toast) => toast.id));'));
  assert.ok(content.includes('if (!liveIds.has(key)) toastNodeMapRef.current.delete(key);'));
  assert.ok(content.includes('if (!liveIds.has(key)) toastExitingRef.current.delete(key);'));
  assert.ok(content.includes('createExplorerDensityController({'));
  assert.ok(content.includes('createPinchDensityController({'));
  assert.ok(content.includes('id="asset-density-slider"'));
  assert.ok(content.includes('data-density-pinch-surface="true"'));
  assert.ok(hookContent.includes('window.requestAnimationFrame(processScroll)'));
  assert.ok(hookContent.includes('const TOPBAR_REVEAL_HYSTERESIS_PX = 20;'));
  assert.ok(hookContent.includes('const suppressAutoToggle = useCallback((ms = TOPBAR_COMPENSATION_SUPPRESS_MS) => {'));
  assert.ok(hookContent.includes('const openInsetPx = getOpenInsetPx();'));
  assert.ok(hookContent.includes('const currentInsetPx = openInsetPx;'));
  assert.ok(hookContent.includes('const contentTopPx = currentTop - currentInsetPx;'));
  assert.ok(!hookContent.includes('if (hiddenRef.current && currentTop <= TOPBAR_REVEAL_AT_TOP_PX) {'));
  assert.ok(hookContent.includes('if (!hiddenRef.current && delta > 0 && contentTopPx >= 0) {'));
  assert.ok(hookContent.includes('if (hiddenRef.current && delta < 0 && contentTopPx <= -TOPBAR_REVEAL_HYSTERESIS_PX) {'));
  assert.ok(content.includes('useLayoutEffect(() => {'));
  assert.ok(styles.includes('will-change: transform, opacity;'));
  assert.ok(styles.includes('transition: opacity 120ms ease;'));
  assert.ok(!styles.includes('transition: transform 160ms ease, opacity 160ms ease;'));
  assert.ok(styles.includes('.topbar,'));
  assert.ok(styles.includes('touch-action: manipulation;'));
  assert.ok(styles.includes('transform: translate3d(0, calc(-1 * var(--topbar-measured-height)), 0);'));
  assert.ok(styles.includes('@media (max-width: 860px){'));
  assert.ok(styles.includes('--topbar-gap: 14px;'));
  assert.ok(!styles.includes('padding-top: 8px;'));
  assert.ok(!styles.includes('padding-top: 6px;'));
});


test('package explorer project chips toggle selected project off to restore all-projects scope', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const content = fs.readFileSync(explorerPath, 'utf8');
  assert.ok(content.includes('const alreadySelected = Boolean(activeProject)'));
  assert.ok(content.includes("activeProject?.name === project.name"));
  assert.ok(content.includes("setActiveProject(null);"));
  assert.ok(content.includes("setMediaScope('all');"));
  assert.ok(content.includes("addToast('good', 'Project', 'Showing all projects');"));
  assert.ok(content.includes("setActiveProject(project);"));
  assert.ok(content.includes("setMediaScope('project');"));
});

test('package explorer sidebar scroll keeps touch scrolling enabled for project panel', () => {
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  assert.ok(styles.includes('.sidebar .scroll{'));
  assert.ok(styles.includes('-webkit-overflow-scrolling: touch;'));
  assert.ok(styles.includes('overscroll-behavior: contain;'));
  assert.ok(styles.includes('touch-action: pan-y;'));
});


test('package explorer conditionally mounts confirm and compose modals with exit presence', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const content = fs.readFileSync(explorerPath, 'utf8');
  assert.ok(content.includes('{deleteModalRendered ? ('));
  assert.ok(content.includes('if (deleteModalOpen) setDeleteModalRendered(true);'));
  assert.ok(content.includes('motion.close(() => setDeleteModalRendered(false));'));
  assert.ok(content.includes('className="confirm-modal open"'));
  assert.ok(!content.includes('aria-hidden={!deleteModalOpen}'));
  assert.ok(content.includes('{composeModalRendered ? ('));
  assert.ok(content.includes('if (composeModalOpen) setComposeModalRendered(true);'));
  assert.ok(content.includes('motion.close(() => setComposeModalRendered(false));'));
  assert.ok(content.includes('className="compose-modal open"'));
  assert.ok(!content.includes('aria-hidden={!composeModalOpen}'));
});


test('package explorer toast layer stays above the fixed topbar stack', () => {
  const stylesPath = path.join(packageRoot, 'src', 'styles.css');
  const styles = fs.readFileSync(stylesPath, 'utf8');
  assert.ok(styles.includes('.toasts{'));
  assert.ok(styles.includes('top: calc(env(safe-area-inset-top, 0px) + 74px);'));
  assert.ok(styles.includes('z-index: 140;'));
});

test('motion architecture keeps density, drawer, toast, and topbar contracts explicit', () => {
  const explorerPath = path.join(packageRoot, 'src', 'ExplorerApp.tsx');
  const densityControllerPath = path.join(packageRoot, 'src', 'explorer', 'density', 'createExplorerDensityController.ts');
  const flipPath = path.join(packageRoot, 'src', 'explorer', 'density', 'animateDensityFlip.ts');
  const drawerMotionPath = path.join(packageRoot, 'src', 'ui', 'motion', 'drawerMotion.ts');
  const topbarMotionPath = path.join(packageRoot, 'src', 'ui', 'motion', 'topbarMotion.ts');
  const content = fs.readFileSync(explorerPath, 'utf8');
  const densityController = fs.readFileSync(densityControllerPath, 'utf8');
  const flip = fs.readFileSync(flipPath, 'utf8');
  const drawerMotion = fs.readFileSync(drawerMotionPath, 'utf8');
  const topbarMotion = fs.readFileSync(topbarMotionPath, 'utf8');

  assert.ok(content.includes("if (view !== 'grid') {"));
  assert.ok(content.includes('const gridEl = gridSurfaceEl;'));
  assert.ok(content.includes('const onSliderInput = () => {'));
  assert.ok(content.includes('density.scrubTo(Number(sliderEl.value || DEFAULT_COLUMNS_MOBILE));'));
  assert.ok(content.includes('const onSliderChange = () => density.settleScrub();'));
  assert.ok(content.includes('step={0.01}'));
  assert.ok(content.includes('toastMotionRef.current?.exit(node, () => removeToast(toast.id));'));
  assert.ok(content.includes('if (inDensityPinchSurface(event.target)) return;'));
  assert.ok(content.includes('data-density-pinch-surface="true"'));
  assert.ok(content.includes('topbarMotionRef.current?.refresh();'));
  assert.ok(content.includes('className="backdrop inspector-backdrop"'));
  assert.ok(content.includes('data-inspector-backdrop="true"'));
  assert.ok(content.includes('data-inspector-drawer="true"'));
  assert.ok(content.includes("const modeQuery = window.matchMedia('(max-width: 860px)');"));
  assert.ok(content.includes("modeQuery.addEventListener('change', handleModeChange);"));
  assert.ok(content.includes('inspectorOpenRef.current = inspectorOpen;'));
  assert.ok(content.includes('if (hasBootstrappedExplorerSession) return;'));
  assert.ok(content.includes('hasBootstrappedExplorerSession = true;'));
  assert.ok(content.includes('if (!node) return;'));
  assert.ok(content.includes('const knownNode = toastNodeMapRef.current.get(toast.id);'));
  assert.ok(content.includes('} else if (knownNode !== node) {'));
  assert.ok(!content.includes('toastNodeMapRef.current.delete(toast.id);'));

  assert.ok(densityController.includes("gridEl.style.setProperty('--masonry-column-count', String(currentColumns));"));
  assert.ok(densityController.includes('scrubTo: (nextValue: number) => void;'));
  assert.ok(densityController.includes('const valueToColumnCount = (nextValue: number) => {'));
  assert.ok(densityController.includes('if (nextValue > previousScrubValue) return Math.floor(nextValue + 1e-6);'));
  assert.ok(densityController.includes('if (nextValue < previousScrubValue) return Math.ceil(nextValue - 1e-6);'));
  assert.ok(densityController.includes('let latestRequestedColumns: number | null = null;'));
  assert.ok(densityController.includes('const requestLatestCommit = (nextColumns: number) => {'));
  assert.ok(densityController.includes('if (rafId) return;'));
  assert.ok(densityController.includes('requestAnimationFrame(flushLatestCommit);'));
  assert.ok(densityController.includes("interactionMode: 'scrub' | 'settle' = 'scrub',"));
  assert.ok(densityController.includes("commitColumns(nextColumns, animated, 'settle');"));
  assert.ok(!densityController.includes("quickSetter(gridEl, 'scale')"));
  assert.ok(!densityController.includes('DENSITY_STEP_HYSTERESIS'));

  assert.ok(!flip.includes('requestAnimationFrame(() => {'));
  assert.ok(flip.includes('const state = Flip.getState(items);'));
  assert.ok(flip.includes('commitLayout();'));
  assert.ok(flip.includes('Flip.from(state, {'));
  assert.ok(flip.includes('absolute: true,'));
  assert.ok(flip.includes('scale: false,'));
  assert.ok(flip.includes("clearProps: 'transform,opacity'"));
  assert.ok(flip.includes('const previous = activeByGrid.get(gridEl);'));
  assert.ok(flip.includes('previous.kill();'));
  assert.ok(flip.includes('onInterrupt: () => {'));

  assert.ok(drawerMotion.includes("export type DrawerPresentationMode = 'side' | 'sheet';"));
  assert.ok(drawerMotion.includes("if (mode === 'sheet') {"));
  assert.ok(drawerMotion.includes('function syncLayoutMode() {'));
  assert.ok(drawerMotion.includes('function setClosedState() {'));
  assert.ok(drawerMotion.includes("drawerEl.dataset.drawerMotionOwned = 'true';"));
  assert.ok(drawerMotion.includes("backdropEl.dataset.drawerMotionOwned = 'true';"));

  assert.ok(topbarMotion.includes('refresh: () => void;'));
  assert.ok(topbarMotion.includes('function refresh() {'));
  assert.ok(topbarMotion.includes('y: -topbarEl.offsetHeight,'));
});
